/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mio.h"


void calculadora_basica_1(char *host, operandos componentes)
{
	CLIENT *clnt;
	float  *result_1;
	operandos suma_1_arg1=componentes;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_BASICA, BASICA_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(suma_1_arg1, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%f+%f=%f",suma_1_arg1.operando1,suma_1_arg1.operando2,*result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void menu_basic(int *op, operandos *comp){//Menú interactivo
	printf("========Calculadora========\n");
	printf("1. Suma\n");
	printf("\nEscoja una operación = ");
	scanf("%d",&op);
	printf("\nIntroduzca los operandos espaciando => ");
	scanf("%f %f",&comp->operando1,&comp->operando2);
}

int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	int operacion;
	operandos componentes;
	menu_basic(&operacion,&componentes);
	host = argv[1];
	calculadora_basica_1 (host,componentes);
exit (0);
}
