/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MIO_H_RPCGEN
#define _MIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_1_argument {
	float arg1;
	float arg2;
};
typedef struct sum_1_argument sum_1_argument;

#define SUMPROG 0x20000001
#define SUMVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  float * sum_1(float , float , CLIENT *);
extern  float * sum_1_svc(float , float , struct svc_req *);
extern int sumprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  float * sum_1();
extern  float * sum_1_svc();
extern int sumprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_1_argument (XDR *, sum_1_argument*);

#else /* K&R C */
extern bool_t xdr_sum_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MIO_H_RPCGEN */
