/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mio.h"

float *
suma_1_svc(operandos arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
resta_1_svc(operandos arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
multiplica_1_svc(operandos arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
divide_1_svc(operandos arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
producto_escalar_1_svc(vectores3d arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

VECTOR3D *
producto_escalar_1_svc(vectores3d arg1,  struct svc_req *rqstp)
{
	static VECTOR3D  result;

	/*
	 * insert server code here
	 */

	return &result;
}
