/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mio.h"

bool_t
xdr_sum_1_argument (XDR *xdrs, sum_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
