/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mio.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static float *
_suma_1 (operandos  *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(*argp, rqstp));
}

static float *
_resta_1 (operandos  *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(*argp, rqstp));
}

static float *
_multiplica_1 (operandos  *argp, struct svc_req *rqstp)
{
	return (multiplica_1_svc(*argp, rqstp));
}

static float *
_divide_1 (operandos  *argp, struct svc_req *rqstp)
{
	return (divide_1_svc(*argp, rqstp));
}

static float *
_producto_escalar_1 (vectores3d  *argp, struct svc_req *rqstp)
{
	return (producto_escalar_1_svc(*argp, rqstp));
}

static VECTOR3D *
_producto_escalar_1 (vectores3d  *argp, struct svc_req *rqstp)
{
	return (producto_escalar_1_svc(*argp, rqstp));
}

static void
calculadora_basica_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		operandos suma_1_arg;
		operandos resta_1_arg;
		operandos multiplica_1_arg;
		operandos divide_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICA:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _multiplica_1;
		break;

	case DIVIDE:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _divide_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_vectorial_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		vectores3d producto_escalar_1_arg;
		vectores3d producto_escalar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectores3d;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_1;
		break;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectores3d;
		_xdr_result = (xdrproc_t) xdr_VECTOR3D;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA_BASICA, BASICA_1);
	pmap_unset (CALCULADORA_VECTORIAL, AVANZADA_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA_BASICA, BASICA_1, calculadora_basica_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA_BASICA, BASICA_1, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA_VECTORIAL, AVANZADA_1, calculadora_vectorial_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA_VECTORIAL, AVANZADA_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA_BASICA, BASICA_1, calculadora_basica_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA_BASICA, BASICA_1, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA_VECTORIAL, AVANZADA_1, calculadora_vectorial_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA_VECTORIAL, AVANZADA_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
