/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mio.h"

float *
sum_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result=arg1+arg2;

	return &result;
}
